server:
  port: 8000

spring:
  application:
    name: cloud-consumer-order
  cloud:
    # 设置超时时间，单位是毫秒
    openfeign:
      client:
        config:
          default:
            # 连接超时时间
            connect-timeout: 5000
            # 读取超时时间
            read-timeout: 5000
            # 日志设置
            logger-level: basic
#          cloud-payment-service:
#            connect-timeout: 5000
#            read-timeout: 3000
      httpclient:
        hc5:
          enabled: true
      compression:
        request:
          enabled: true
          min-request-size: 2048 # 最小触发压缩大小
          mime-types: text/xml,application/xml,application/json #触发压缩数据类型
        response:
          enabled: true
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}

logging:
  level:
    com:
      atguigu:
        cloud:
          apis:
            PayFeignApi: debug